name: CI pipeline

run-name: ${{ github.event.head_commit.message }}

on: [push]

jobs:
  Unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout subrepos
        run: git submodule init; git submodule update
      - name: Install Ninja
        run: sudo apt-get update -y; sudo apt-get install -y ninja-build
      - name: Set file permissions
        run: chmod +x build.sh test.sh 
      - name: Build
        run: ./build.sh  
      - name: Run tests
        run: ./test.sh
